// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Signalr.Models
{
    public partial class Zamowienia
    {
        public int Za_Id { get; set; }
        public string Za_Nr_Zamowienia { get; set; }
        public string Za_Nazwa { get; set; }
        public string Za_Odbiorca { get; set; }
    }
}